### PR TITLE
Added stop-app documentation

### PR DESCRIPTION
**Pull request by anshbansal**
Docs for stop-app added in https://github.com/grails/grails-core/issues/641

### CODE REVIEW

**Comment by anshbansal** [comment]
@graemerocher Is the flag in the commands all the command line args that are supported? If yes, then I can improve the docs for commands now I know where the source is.

**Comment by graemerocher** [comment]
Rather than `-Dserver.port` it is better `port` and `host`:

     grails stop-app --port=9090 --host=blah

**Comment by anshbansal** [comment]
Any other change required?

**Comment by graemerocher** [comment]
No, perfect. Thanks!

**Pull request merged**
