### PR TITLE
Update multipleDatasources.adoc

### PR DESCRIPTION
**Pull request by kovacicluka**
As in org.grails.plugins.datasource.DataSourceGrailsPlugin, configuration name is `grails.transaction.chainedTransactionManager`.

### CODE REVIEW

**Comment by puneetbehl** [comment]
Please sign the CLA.

**Review by matrei — DISMISSED** [review]
Good catch! There are actually two more places where `chainedTransactionManagerPostProcessor` should be changed.

https://github.com/grails/grails-doc/blob/0da43fe46512992fbc0c940cc6f196af4b923264/src/en/guide/conf/dataSource/multipleDatasources.adoc?plain=1#L248

https://github.com/grails/grails-doc/blob/0da43fe46512992fbc0c940cc6f196af4b923264/src/en/guide/conf/dataSource/multipleDatasources.adoc?plain=1#L254

Would you mind changing these as well in this PR?

**Comment by jamesfredley** [comment]
I'll submit those other 2 changes in another PR.

**Comment by jamesfredley** [comment]
And then will merging branches up to 7.0.x

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-doc/pull/916

**Pull request merged**
