### PR TITLE
Fix quickreference guide links

### PR DESCRIPTION
**Pull request by rpalcolea**
Fixes broken links between Quick Reference and the Guide.

Example:  http://docs.grails.org/latest/ref/Plug-ins/URL%20mappings.html in

> Refer to the section on URL Mapping in the Grails user guide which details Grails' URL mappings.

If you click "URL Mapping” it doesn’t take you to http://docs.grails.org/latest/guide/theWebLayer.html#urlmappings anymore

### CODE REVIEW

**Comment by graemerocher** [comment]
Could you submit to the 3.1.x branch?

**Comment by rpalcolea** [comment]
Hi @graemerocher!

Sure!

I'll take a look during the day on this. Looks like there are difference between the quick reference source files in `master` and `3.1.x` https://github.com/grails/grails-doc/compare/3.1.x...master

I need to check if the differences only apply to Grails 3.2+. question: If I open the pull request to the 3.1.x, will the changes appear on the latest guide? or should I keep both pull requests?

Any suggestion to keep this consistent?

**Comment by graemerocher** [comment]
yes 3.1.x gets merged into 3.2.x etc.

**Comment by rpalcolea** [comment]
Alright, opened https://github.com/grails/grails-doc/pull/504

**Pull request closed without merging**
