### PR TITLE
Corrected path to Java src in Grails 3 migration guide

### PR DESCRIPTION
**Pull request by domurtag**

### CODE REVIEW

**Comment by graemerocher** [comment]
What is the reason or need to split the src/main/java and src/main/groovy directories? It was needed in the past when there was no joint compilation, but now you can put Java and Groovy classes in src/main/groovy and all is fine.

**Comment by domurtag** [comment]
It's somewhat surprising to find java files under `src/main/groovy`, but if that's your intention, then fair enough.

I assumed that the java files should be in `src/main/java` because that what the instructions in the [upgrade guide](https://grails.github.io/grails-doc/latest/guide/upgrading.html) indicate

````
# first the sources
cp -rf ../quartz-2.x/src/groovy src/main/groovy
cp -rf ../quartz-2.x/src/java src/main/java
````
So if `src/main/groovy` is intended to be the root dir for java and groovy source, the upgrade guide should be corrected.

**Comment by graemerocher** [comment]
Agree, the upgrade guide should be corrected

**Comment by domurtag** [comment]
OK, I'll submit a new PR that fixes the upgrade guide

**Comment by domurtag** [comment]
Based on my misunderstanding of the structure of a Grails 3 app caused by this error in the upgrade guide I opened this issue:

https://jira.grails.org/browse/GRAILS-12069

It should be closed

**Comment by domurtag** [comment]
## Aside

@graemerocher on a related topic, I'm in the process of writing a plugin that will partially automate the process of upgrading a Grails 2 plugin or app to Grails 3

https://github.com/domurtag/migrate-2-grails3

It's not complete yet, but I've opened a couple of issues with questions about Grails 3 that you might be able to help me with. If you think this might be useful, any feedback you might have would be much appreciated.

**Pull request closed without merging**
