### PR TITLE
GRAILS-9839 - Add the possibility of get a ScrollableResults object from named queries - Documentation

### PR DESCRIPTION
**Pull request by ivogallego**
Url to the issue: http://jira.grails.org/browse/GRAILS-9839

Related to the previous pull request

### CODE REVIEW

**Comment by jeffbrown** [comment]
@ivogallego Has this feature been implemented?

**Comment by ivogallego** [comment]
@jeffbrown I don't think so... Was accepted but never merged :(

**Comment by graemerocher** [comment]
@ivogallego Where is the original pull request for the feature? Trying to track it down...

**Comment by ivogallego** [comment]
This is it,  but after so long probably will be impossible to merge. Am I right?

**Pull request closed without merging**
