### PR TITLE
Fix for grails.home set to not cause source to be fetched

### PR DESCRIPTION
**Pull request by anshbansal**
Fix https://github.com/grails/grails-doc/issues/339

### CODE REVIEW

**Comment by anshbansal** [comment]
Seems there is a problem. I will fix it today.

**Comment by graemerocher** [comment]
The fix doesn't seem to work on the CI server

**Comment by anshbansal** [comment]
@graemerocher  I noticed that. Will send an updated PR.

**Comment by rlovtangen** [comment]
Thanks, @anshbansal.
Would have been great to have this property in a file not under source control, though. gradle.properties is under source control, so when setting grails.home there, you need to make sure to not accidentally commit the change.

**Comment by jeffbrown** [comment]
I think @rlovtangen makes a good point.  Can we get this pulled out into a separate properties file?

**Comment by graemerocher** [comment]
@jeffbrown @rlovtangen Why can't it just go into `~/.gradle/gradle.properties` rather than adding more complexity?

**Comment by rlovtangen** [comment]
@graemerocher yes, that's good enough for me. Needs to update patchesDoc.gdoc, then.

**Comment by anshbansal** [comment]
updated the docs

**Pull request merged**
