### PR TITLE
Added Cloud Deployment page with Boxfuse and AWS section

### PR DESCRIPTION
**Pull request by axelfontaine**
This page should be extended with other providers in the future. This PR supersedes #475

### CODE REVIEW

**Comment by axelfontaine** [comment]
@graemerocher Is anything still standing in the way of merging this?

**Comment by graemerocher** [comment]
I guess the main issue is that it is titled AWS deployment, but doesn't use plain AWS but instead Boxfuse which could be confusing. If there was a dedicated AWS section and a Boxfuse section it may make more sense to merge.

**Comment by axelfontaine** [comment]
Well plain AWS is a little hard to define these days as it could be OpsWorks, ECS, CodeDeploy, Elastic Beanstalk, CloudFormation, ...

This page could provide a base where you could then receive contributions for Heroku, PWS, or any of the AWS services I mentioned. At the end of the day, the current section title makes it pretty clear that this is using Boxfuse to deploy to AWS and not some other AWS service.

What do you think?

**Comment by erichelgeson** [comment]
Closing due to age - and think it'd be better as a blog post/guide/etc.

**Pull request closed without merging**
