### PR TITLE
fieldError document added to grils docs

### PR DESCRIPTION
**Pull request by guramritpal-jft**
Issue https://github.com/grails/grails-doc/issues/281 missing fieldError tag documentation has been added.

### CODE REVIEW

**Comment by guramritpal-jft** [comment]
@jeffbrown  @anshbansal  i have added the fieldError.gdoc  just review once

**Comment by anshbansal** [comment]
@guramritpal-jft There is no need for eg.  in the code. For the optionals if there are defaults specify them. 

Also sending PRs via branches other than master is preferable. Because you making changes to master does not automatically add more commits in PR.

Also have you checked whether the javadocs in the code are correct as per functionality? I mean I thought the javadoc was wrong due to which I created https://github.com/grails/grails-doc/issues/281

**Comment by guramritpal-jft** [comment]
yes u can close this issue.

**Comment by jeffbrown** [comment]
@anshbansal 

> Also sending PRs via branches other than master is preferable.

I really don't care what the name of the branch at the other end is.  It doesn't really matter.  It is problematic if additional unrelated commits are added to that branch between the time that the PR is sent and when it is applied, but that is true regardless of what the branch name is.  If someone wants to use `master` because they don't anticipate making other changes on that branch, that is fine.  From our end, the name of the branch at the other end is of no consequence.

**Pull request merged**
